Blog_project/Blog_app/urls.py
from django.urls import path
from . import views

app_name = 'Blog_app'

urlpatterns = [
    path('', views.home, name='home'),
    # path('create-author/', views.create_author, name='create-author'),
    path('recent-posts/', views.recent_posts, name='recent-posts'),
    path('posts-detail/<int:post_id>', views.detail_post, name='posts-detail'),
    path('posts-under-category/<int:cat_id>', views.posts_under_category, name='posts-under-category'),
    path('create-post/', views.create_post, name='create-post'),
    path('create-category/', views.create_category, name='create-category'),
]

Blog_project/Blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Login_app.urls')),
    path('', include('Blog_app.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog_project/Login_app/urls.py
from django.urls import path
from . import views

app_name = 'Login_app'

urlpatterns = [
    path('signup/', views.sign_up_user, name='signUp'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.log_out_user, name='logout'),
    path('profile/', views.user_profile, name='user_profile'),
    path('edit-profile/', views.edit_user_profile, name='edit_user_profile'),
    path('change-pro-pic/', views.change_pro_pic, name='change_pro_pic'),
]

Blog_project/Blog_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Categories'


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, models.CASCADE)
    title = models.CharField(max_length=200)
    post_slug = models.SlugField(max_length=200, unique=True)
    post_img = models.ImageField(upload_to='post_img', null=True, blank=True)
    post_content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_comments')
    comment_text = models.TextField()
    commented_on = models.DateTimeField(auto_now_add=True)
    update_comment = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.comment_text

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liked_user')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='liked_post')

Blog_project/Login_app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pics', null=True, blank=True)

Blog_project/Blog_app/forms.py
from django import forms
from .models import *


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'category', 'post_img', 'post_content']

Blog_project/Blog_app/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic import TemplateView, ListView, CreateView, DetailView
from .models import *
from .forms import *
import uuid



def home(request):
    categories = Category.objects.all()
    post = Post.objects.all()[0]
    posts_all = Post.objects.all()
    recent_post = Post.objects.all()[0:5]

    paginator = Paginator(posts_all, 4)
    page_number = request.GET.get('page')
    posts_all = paginator.get_page(page_number)

    context = {
        'categories': categories,
        'post': post,
        'posts_all': posts_all,
        'recent_post': recent_post
    }
    return render(request, 'blog/home.html', context)



def recent_posts(request):
    posts = Post.objects.all()[0:10]
    categories = Category.objects.all()

    context = {
        'posts': posts,
        'categories': categories,
    }
    return render(request, 'blog/recent_posts.html', context)


def detail_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    categories = Category.objects.all()
    context = {
        'post': post,
        'categories': categories
    }
    return render(request, 'blog/detail_post.html', context)


def posts_under_category(request, cat_id):
    category = Category.objects.get(pk=cat_id)
    posts = category.post_set.all()
    categories = Category.objects.all()

    context = {
        'posts': posts,
        'categories': categories
    }
    return render(request, 'blog/posts_under_category.html', context)


def create_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            form.save()
            messages.info(request, f"Category '{title}' added successfully !")
            return HttpResponseRedirect(reverse('Blog_app:home'))

    context = {
        'form': form
    }
    return render(request, 'blog/create_category.html', context)



def create_post(request):
    form = CreatePostForm()
    if request.method == 'POST':
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post_obj = form.save(commit=False)
            post_obj.author = request.user
            title = post_obj.title
            post_obj.post_slug = title.replace(" ", "-") + "-" + str(uuid.uuid4())
            post_obj.save()

            return HttpResponseRedirect(reverse('Blog_app:home'))


    context = {
        'form': form
    }
    return render(request, 'blog/create_post.html', context)

Blog_project/Login_app/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from .decorators import unauthenticated_user
from django.contrib.auth.forms import UserCreationForm


@unauthenticated_user
def sign_up_user(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('Login_app:login'))

    context = {
        'form': form
    }
    return render(request, 'account/signUp.html', context)


@unauthenticated_user
def login_user(request):
    form = AuthenticationForm()
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            print(username)
            print(password)
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('Blog_app:home'))

    context = {
        'form': form
    }
    return render(request, 'account/login.html', context)



@login_required
def log_out_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_app:login'))

@login_required
def user_profile(request):
    return render(request, 'account/profile.html')

@login_required
def edit_user_profile(request):
    return render(request, 'account/edit_profile.html')

@login_required
def change_pro_pic(request):

    return render(request, 'account/change_pro_pic.html')

Blog_project/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title_block %} {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'resources/css/main.css' %}" />
  </head>
  <body>
    <header>
      <div class="container container-flex">
        <a href="{% url 'Blog_app:home' %}">
          <div class="site-title">
          <h1>My Blog Site</h1>
          <p class="subtitle">blogging is my hobby</p>
        </div>
        </a>
        <nav>
          <ul>
            <li><a class="current-page" href="{% url 'Blog_app:home' %}">Home</a></li>
            <li><a href="{% url 'Blog_app:recent-posts' %}">Recent Post</a></li>
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'Login_app:logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'Login_app:login' %}">Login</a></li>
            {% endif %}
            </li>
          </ul>
        </nav>
      </div>
    </header>

    <div class="container container-flex">
      <main role="main">

        {% if messages %}
          {% for message in messages %}
             <div {% if message.tags %} class="alert alert-{{ message.tags }} {% endif %}" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              </div>
          {% endfor %}
        {% endif %}

        {% block content_block %}

        {% endblock %}
      </main>
      {% include 'sidebar.html' %}
    <footer>
      <p>My Blog Site</p>
      <p>Copyright 2020</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

Blog_project/templates/blog/create_author.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Create author {% endblock %}

{% block content_block %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-info btn-sm" value="Create">
    </form>
{% endblock %}

Blog_project/templates/blog/create_category.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Create Category {% endblock %}

{% block content_block %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-info btn-sm" value="Save">
    </form>
{% endblock %}

Blog_project/templates/blog/create_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} home {% endblock %}

{% block content_block %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-info btn-sm" value="Save">
    </form>
{% endblock %}

Blog_project/templates/blog/detail_post.html
{% extends 'base.html' %}

{% block title_block %} Post detail {% endblock %}

{% block content_block %}
    <article class="article-featured">

          <h2 class="article-title">Lorem ipsum dolor sit amet.</h2>
         {% if post.post_img %}
          <div class="img">
             <img src="{{ post.post_img.url }}" alt="" class="article-image" />
           </div>
         {% else %}
        <div class="img">
        <img
            src="https://www.pongboss.com/wp-content/uploads/2017/09/nutrition-cover-1024x700.jpg"
            alt=""
            class="article-image"
          />
            </div>
         {% endif %}
          <p class="article-info">{{ post.created_at }}</p>
          <p class="article-body">
            {{ post.post_content|linebreaks }}
          </p>

        </article>
{% endblock %}

Blog_project/templates/blog/home.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} home {% endblock %}

{% block content_block %}
    <article class="article-featured">

          <h2 class="article-title">Lorem ipsum dolor sit amet.</h2>
         {% if post.post_img %}
          <div class="img">
             <img src="{{ post.post_img.url }}" alt="" class="article-image" />
           </div>
         {% else %}
        <div class="img">
        <img
            src="https://www.pongboss.com/wp-content/uploads/2017/09/nutrition-cover-1024x700.jpg"
            alt=""
            class="article-image"
          />
            </div>
         {% endif %}
          <p class="article-info">{{ post.created_at }}</p>
          <p class="article-body">
            {{ post.post_content|range_filter|linebreaks }}
          </p>

        </article>
        {% for post in posts_all %}
        <article class="article-recent">

          <div class="article-recent-main">

            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-body">
              {{ post.post_content|range_filter }}
            </p>
            <a href="{% url 'Blog_app:posts-detail' post_id=post.pk %}" class="article-read-more">CONTINUE READING</a>
          </div>
          <div class="article-recent-secondary">
            {% if post.post_img %}
           <div class="img">
             <img src="{{ post.post_img.url }}" alt="" class="article-image" />
           </div>
         {% else %}
        <img
            src="https://www.pongboss.com/wp-content/uploads/2017/09/nutrition-cover-1024x700.jpg"
            alt=""
            class="article-image"
          />
         {% endif %}
            <p class="article-info">{{ post.created_at }}</p>
          </div>

        </article>
{% endfor %}
            <div class="pagination">
              {% if posts_all.has_previous %}
              <a href="?page={{ posts_all.previous_page_number }}" data-color="red">&laquo;</a>
              {% endif %}
                 {% for num in posts_all.paginator.page_range %}
                  {% if posts_all.number == num %}
                    <a href="?page={{ num }}" class="active">{{ num }}</a>
                  {% else %}
                    <a href="?page={{ num }}">{{ num }}</a>
                  {% endif %}
                {% endfor %}
              {% if posts_all.has_next %}
              <a href="?page={{ posts_all.next_page_number }}">&raquo;</a>
              {% endif %}
            </div>


{% endblock %}

Blog_project/templates/blog/posts_under_category.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} Recent post {% endblock %}

{% block content_block %}
        {% for post in posts %}
        <article class="article-recent">

          <div class="article-recent-main">

            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-body">
              {{ post.post_content|range_filter }}
            </p>
            <a href="{% url 'Blog_app:posts-detail' post_id=post.pk %}" class="article-read-more">CONTINUE READING</a>
          </div>
          <div class="article-recent-secondary">
            {% if post.post_img %}
           <div class="img">
             <img src="{{ post.post_img.url }}" alt="" class="article-image" />
           </div>
         {% else %}
        <img
            src="https://www.pongboss.com/wp-content/uploads/2017/09/nutrition-cover-1024x700.jpg"
            alt=""
            class="article-image"
          />
         {% endif %}
            <p class="article-info">{{ post.created_at }}</p>
          </div>

        </article>
{% endfor %}

{% endblock %}

Blog_project/templates/blog/recent_posts.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} Recent post {% endblock %}

{% block content_block %}
        {% for post in posts %}
        <article class="article-recent">

          <div class="article-recent-main">

            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-body">
              {{ post.post_content|range_filter }}
            </p>
            <a href="{% url 'Blog_app:posts-detail' post_id=post.pk %}" class="article-read-more">CONTINUE READING</a>
          </div>
          <div class="article-recent-secondary">
            {% if post.post_img %}
           <div class="img">
             <img src="{{ post.post_img.url }}" alt="" class="article-image" />
           </div>
         {% else %}
        <img
            src="https://www.pongboss.com/wp-content/uploads/2017/09/nutrition-cover-1024x700.jpg"
            alt=""
            class="article-image"
          />
         {% endif %}
            <p class="article-info">{{ post.created_at }}</p>
          </div>

        </article>
{% endfor %}

{% endblock %}

Blog_project/templates/sidebar.html
{% load custom_filters %}

<aside class="sidebar">
    {% if request.user.is_authenticated %}
        <div class="sidebar-widget">
           <h2 class="widget-title">Category</h2>
          <ul>
            {% for category in categories %}
            <li><a href="{% url 'Blog_app:posts-under-category' cat_id=category.pk %}">{{ category.title }}</a></li>
            {% endfor %}
          </ul>
        </div>
        <div class="sidebar-widget">
          <ul>
            <li><a href="">Create Author</a></li>
            <li><a href="{% url 'Blog_app:create-category' %}">Create Category</a></li>
            <li><a href="{% url 'Blog_app:create-post' %}">Create Post</a></li>
          </ul>
        </div>
        {% endif %}
        <div class="sidebar-widget">
          <h2 class="widget-title">RECENT POST</h2>
         {% for post in recent_post %}
          <div class="widget-recent-post">
            <h3 class="widget-recent-post-title">{{ post.title|range_title_filter }}</h3>
            <div class="img">
              <img
              src="https://www.pongboss.com/wp-content/uploads/2017/09/nutrition-cover-1024x700.jpg"
              alt=""
              class="widget-image"
            />
            </div>
          </div>
          {% endfor %}
        </div>
      </aside>
</div>